@startuml datamodel

!define table(name, desc) class name as "desc"
!define primary_key(x) <b>x</b>
!define foreign_key(x) #x

table(User, "User") {
    primary_key(id): int
    email: string
    roles: array
    password: string
    isVerified: boolean
    fullname: string
    photo: string
    tasks: task[]
}

table(Task, "Task") {
    primary_key(id): int
    createdAt: datetime
    title: string
    content: string
    isDone: boolean
    foreign_key(created_by): User
}

User "1" -- "0..*" Task : created_by

@enduml
