@startuml usecase
!define RECTANGLE class

actor User
actor Admin

usecase "View Home Page" as UC1
usecase "View Task List" as UC2
usecase "Create Task" as UC3
usecase "Edit Task" as UC4
usecase "Toggle Task Status" as UC5
usecase "Delete Task" as UC6
usecase "Login" as UC7
usecase "Register" as UC8
usecase "Reset Password" as UC9
usecase "Logout" as UC10
usecase "View Admin Panel" as UC11
usecase "View User Details" as UC12
usecase "Edit User Roles" as UC13
usecase "Delete User" as UC14

User -down-> UC1
User -down-> UC2
User -down-> UC3
User -down-> UC4
User -down-> UC5
User -down-> UC6
User -down-> UC7
User -down-> UC8
User -down-> UC9
User -down-> UC10

Admin -down-> UC11
Admin -down-> UC12
Admin -down-> UC13
Admin -down-> UC14

UC1 -[#white,dotted]-> UC2
UC2 -[#white,dotted]-> UC5
UC5 -[#white,dotted]-> UC8
UC3 -[#white,dotted]-> UC6
UC6 -[#white,dotted]-> UC9
UC4 -[#white,dotted]-> UC7
UC7 -[#white,dotted]-> UC10
UC11 -[#white,dotted]-> UC12
UC12 -[#white,dotted]-> UC13
UC13 -[#white,dotted]-> UC14

'ORGANIZE_USECASE_GRID'
@enduml